services:
    _defaults:
        autowire: true
        autoconfigure: true

    Optime\Util\:
        resource: './'

    Optime\Util\Translation\DefaultLocalesProvider:
        arguments:
            - "%optime.sf_utils.default_locale%"
            - "%optime.sf_utils.locales%"
