services:
    _defaults:
        autowire: true
        autoconfigure: true

    Optime\Util\:
        resource: '../../'

    Optime\Util\Translation\DefaultLocalesProvider:
        arguments:
            - "%optime.sf_utils.default_locale%"
            - "%optime.sf_utils.locales%"

    Optime\Util\Http\EventListener\HandleAjaxFormListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.controller' }
            - { name: 'kernel.event_listener', event: 'kernel.response' }

    Optime\Util\Http\EventListener\HandleAjaxViewListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.controller' }
            - { name: 'kernel.event_listener', event: 'kernel.response' }

    Optime\Util\Twig\Loader\AjaxFileLoader:
        autoconfigure: false
        arguments:
            - ""